secret:
  name: {{ .Name }}-credentials
  runsOn: {{ .Name }}-schema
  runsOnList: [{{ .Name }}-schema]
  data:
    url: {{ .Values.url }}

configMap:
  name: {{ .Name }}-config
  runsOn: {{ .Name }}-schema
  schemas:
    schema.sql: {{ .Values.schema }}
    {{- if .Values.seed }}
    seed.sql: {{ .Values.seed }}
    {{- end }}

{{- if .Values.seed }}
seedPgJob:
  name: {{ .Name }}-seed
  runsOn: {{ .Name }}-database
  secretName: {{ .Name }}-credentials
  cmName: {{ .Name }}-config
{{- end }}

atlasSchema:
  name: {{ .Name }}-schema
  runsOn: {{ .Name }}-database
  secretKey: url
  secretName: {{ .Name }}-credentials
  schemaCMName: {{ .Name }}-config
  schemaCMKey: schema.sql

database:
  name: {{ .Name }}-database
  cluster: {{ .Values.cluster | default "database-cluster" }}
  databaseReclaimPolicy: {{ .Values.databaseReclaimPolicy | default "retain" }}
